### ISSUE TITLE
admob_easy

### ISSUE THREAD

**Issue by hibooTest** [matifdeveloper/admob_easy#4]
hi
I am encountering an issue when using the admob_easy package in my project. The code works perfectly when I remove the package from my pubspec.yaml file, but with it included, I experience problems.

i think it is about the async_preferences package 
Error is:

Execution failed for task ':async_preferences:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).

**Comment by matifdeveloper** [comment]
In android app level build.gradle change

```
android {
    compileSdk 34

    compileOptions {
        sourceCompatibility = 17
        targetCompatibility = 17
    }
```

**Comment by hibooTest** [comment]
this is not working
